# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-RDF
version:      0.10
version_from: RDF.pm
installdirs:  site
requires:
    Class::DBI:                    0.95
    DBD::SQLite:                   0.29
    RDF::Simple:                   0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
